### PR TITLE
Fixes updateUserGroup cannot clear the description and the default channels

### LINKED ISSUE #1081: updateUserGroup cannot clear the description and the default channels
### What happened

We cannot clear the description and the default channels of usergroups because the current `updateUserGroup` ignores empty strings.

### Expected behavior

We can clear the description and the default channels of usergroups.

### Steps to reproduce

- Call `UpdateUserGroup` with an usergroup instance that has an empty Description and/or an empty Channels.

#### reproducible code

```
userGroup := slack.CreateUserGroup(UserGroup {
  Name: "name",
  Description: "description",
})

userGroup.Description = ""

updatedUserGroup := slack.UpdateUserGroup(userGroup)

updatedUserGroup.Description # "description"
```

### Versions
- Go: `go1.18.3 darwin/amd64`
- slack-go/slack: `0.11.0`

### PR DESCRIPTION
**Pull request by jmatsu**
Fix: https://github.com/slack-go/slack/issues/1081

## Expected

We can clear the description and the default channels of usergroups by sending empty strings.

## Actual

`updateUserGroup` ignores empty strings so this never sends empty strings to the server.

## Examples

The followings are examples using `curl`. ref: https://api.slack.com/methods/usergroups.update

*Set Up*

> curl -F token=... -F usergroup=SJ6JQHVBN --url 'https://slack.com/api/usergroups.update' -F description="this is a description" -F handle="zz__test_usergroup" -F name="this is a name" -F channels=C92MKCRPU
> {"usergroup":{"id":"SJ6JQHVBN","name":"this is a name","description":"this is a description","handle":"zz__test_usergroup","prefs":{"channels":["C92MKCRPU"],"groups":[]}}, ...}

*Clear the default channels*

> curl -F token=... -F usergroup=SJ6JQHVBN --url 'https://slack.com/api/usergroups.update' -F description="this is a description" -F handle="zz__test_usergroup" -F name="this is a name" -F channels=
> {"usergroup":{"id":"SJ6JQHVBN","name":"this is a name","description":"this is a description","handle":"zz__test_usergroup","prefs":{"channels":[],"groups":[]}}, ...}

*Clear the description*

> curl -F token=... -F usergroup=SJ6JQHVBN --url 'https://slack.com/api/usergroups.update' -F description= -F handle="zz__test_usergroup" -F name="this is a name" -F channels=
> {"usergroup":{"id":"SJ6JQHVBN","name":"this is a name","description":"","handle":"zz__test_usergroup","prefs":{"channels":[],"groups":[]}}, ...}

---

##### PR preparation

✅ Ran `make pr-prop` on HEAD (38367d1)

##### Should this be an issue instead
- [x] No ~is it a convenience method? (no new functionality, streamlines some use case)~
- [x] No ~exposes a previously private type, const, method, etc.~
- [x] No ~is it application specific (caching, retry logic, rate limiting, etc)~
- [x] No ~is it performance related.~

##### API changes

Since API changes have to be maintained they undergo a more detailed review and are more likely to require changes.

- ~no tests, if you're adding to the API include at least a single test of the happy case.~
  - I have added the test cases for updateUserGroup 
- If you can accomplish your goal without changing the API, then do so.
  - Please let me know if you prefer a way to deprecate the current methods and create new ones.
- ~dependency changes. updates are okay. adding/removing need justification.~
  - Nothing.

###### Examples of API changes that do not meet guidelines:

N/A

### CODE REVIEW

File: usergroups.go [hunk 1]
```diff
@@ -183,32 +184,77 @@ func (api *Client) GetUserGroupsContext(ctx context.Context, options ...GetUserG
...
+
+// UpdateUserGroupsOptionDescription change the description of the User Group. (default: nil, so it's no-op)
+func UpdateUserGroupsOptionDescription(description *string) UpdateUserGroupsOption {
+	return func(params *UpdateUserGroupsParams) {
+		params.Description = description
+	}
+}
+
+// UpdateUserGroupsOptionChannels change the default channels of the User Group. (default: nil, so it's no-op)
+func UpdateUserGroupsOptionChannels(channels *[]string) UpdateUserGroupsOption {
```
Comment (kanata2) [inline usergroups.go]: I think the type of channels should be `[]string`.

File: usergroups.go [hunk 2]
```diff
@@ -183,32 +184,77 @@ func (api *Client) GetUserGroupsContext(ctx context.Context, options ...GetUserG
...
 
-	if userGroup.Handle != "" {
-		values["handle"] = []string{userGroup.Handle}
+	if params.Handle != "" {
+		values["handle"] = []string{params.Handle}
 	}
 
-	if userGroup.Description != "" {
-		values["description"] = []string{userGroup.Description}
+	if !reflect.ValueOf(params.Description).IsNil() {
```
Comment (kanata2) [inline usergroups.go]: [question]
Why do you use `reflect.ValueOf` and `reflect.Value.IsNil`?
I think you can use `params.Description == nil` in this case.

**Review by kanata2 — COMMENTED** [review]
Thanks for your PR and sorry for delay🙏

File: usergroups.go (hunk 2 above)
Comment (jmatsu) [reply usergroups.go]: That was my misunderstanding. Thanks!

**Comment by jmatsu** [comment]
@kanata2 Thanks for your review. Could you please have a look again?

**Review by kanata2 — APPROVED** [review]
Thanks. LGTM!

**Comment by kanata2** [comment]
Released! https://github.com/slack-go/slack/releases/tag/v0.11.2
